source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '10.0'

target 'NLAdSDK_Example' do
  pod 'NLAdSDK', :path => '../'

  target 'NLAdSDK_Tests' do
    inherit! :search_paths
  end
end
